<?php

define('LEVIATHAN_SLOTS', [
    2 => 1,
    3 => 1,
    4 => 2,
    5 => 3,
    6 => 4,
    7 => 5,
    8 => 6,
    9 => 7,
    10 => 8,
    11 => 9,
    12 => 9,
]);

const LEVIATHAN_SLOTS_LABELS = [
    1 => '2/3', 
    2 => '4', 
    3 => '5', 
    4 => '6', 
    5 => '7', 
    6 => '8', 
    7 => '9', 
    8 => '10', 
    9 => '11/12'
];

/*
 * State constants
 */
define('ST_BGA_GAME_SETUP', 1);

define('ST_PRE_TURN', 19);
define('ST_PLAYER_PLOT_AT_COURT', 2);
define('ST_PLAYER_ACTION', 3);
define('ST_PLAYER_SECOND_STACK', 32);
define('ST_PRE_PURCHASE', 4);
define('ST_PLAYER_PURCHASE', 5);
define('ST_PRE_EXPLORE', 6);
define('ST_PLAYER_POST_PURCHASE_DISCARD', 62);
define('ST_POST_PURCHASE', 61);
define('ST_PLAYER_EXPLORE', 7);
define('ST_PLAYER_EXPLORE2', 71);
define('ST_PLAYER_EXPLORE3', 72);
define('ST_PRE_CONTROL', 8);
define('ST_PLAYER_CONTROL', 9);
define('ST_NEXT_PLAYER', 10);
define('ST_PLAYER_CHOOSE_MONSTER_REWARD', 11);
define('ST_PLAYER_RECRUIT_PAY', 12);
define('ST_PLAYER_AFFILIATE', 13);
define('ST_PLAYER_LORD_EFFECT', 14);
define('ST_PLAYER_CLEANUP_DISCARD', 15);
define('ST_PLAYER_CONTROL_POST_DRAW', 16);
define('ST_PLAYER_LOCATION_EFFECT_BLACK_SMOKERS', 17);
define('ST_PLAYER_UNUSED_LORDS', 18);
define('ST_PLAYER_MARTIAL_LAW', 20);
define('ST_PLAYER_FILL_SANCTUARY', 21);
define('ST_MULTIPLAYER_GIVE_KRAKEN', 22);
define('ST_PLAYER_PLACE_SENTINEL', 23);
define('ST_PLAYER_PLACE_KRAKEN', 24);

const ST_PLAYER_CHOOSE_LEVIATHAN_TO_FIGHT = 30;
const ST_PLAYER_CHOOSE_ALLY_TO_FIGHT = 31;
const ST_PLAYER_INCREASE_ATTACK_POWER = 39; // 32 taken!!!
const ST_PLAYER_CHOOSE_FIGHT_REWARD = 33;
const ST_PLAYER_CHOOSE_FIGHT_AGAIN = 34;
const ST_MULTIPLAYER_APPLY_LEVIATHAN_DAMAGE = 35;
const ST_AFTER_APPLY_LEVIATHAN_DAMAGE = 36;
const ST_PLAYER_CHOOSE_REVEAL_REWARD = 37;
const ST_PLAYER_CHOOSE_COUNCIL_STACK_MONSTER_TOKEN = 38;
// 39 taken !
const ST_PLAYER_REVEAL_MONSTER_TOKEN = 40;

define('ST_MULTI_LORD2', 102);
define('ST_PLAYER_LORD4', 104);
define('ST_MULTI_LORD5', 105);
define('ST_PLAYER_LORD7', 107);
define('ST_PLAYER_LORD16', 116);
define('ST_PLAYER_LORD19', 119);
define('ST_PLAYER_LORD19B', 1192);
define('ST_PLAYER_LORD22', 122);
define('ST_PLAYER_LORD23', 123);
define('ST_PLAYER_LORD23B', 1232);
define('ST_PLAYER_LORD26', 126);
define('ST_PLAYER_LORD12', 112);
define('ST_PLAYER_LORD17', 117);
define('ST_PLAYER_LORD21', 121);
define('ST_PLAYER_LORD104', 1104);
define('ST_PLAYER_LORD112', 1112);
define('ST_PLAYER_LORD114', 1114);
define('ST_MULTI_LORD114', 1194);
define('ST_PLAYER_LORD116', 1116);
define('ST_PLAYER_LORD202', 1202);
define('ST_PLAYER_LORD206', 1206);
define('ST_PLAYER_LORD208', 1208);
define('ST_PLAYER_LORD210', 1210);

define('ST_PRE_SCORING', 95);
define('ST_FINAL_SCORING', 98);
define('ST_END_GAME', 99);
define('END_SCORE', 100);

/**
 * Game options
 */
define('KRAKEN_EXPANSION', 110);
define('LEVIATHAN_EXPANSION', 120);

/**
 * Constants
 */
define('MARTIAL_LAW_ACTIVATED', 'MARTIAL_LAW_ACTIVATED');
define('LAST_LOCATION', 'LAST_LOCATION');
define('KRAKEN', 'KRAKEN');
define('SCOURGE', 'SCOURGE');
define('SELECTED_FACTION', 'SELECTED_FACTION');
define('AFTER_PLACE_SENTINEL', 'AFTER_PLACE_SENTINEL');
define('AFTER_GIVE_KRAKEN_FINAL_SCORE', 'AFTER_GIVE_KRAKEN_FINAL_SCORE');


/**
 * Global variables
 */
define('SENTINELS', 'SENTINELS');
define('MUST_SELECT_NEW_PLAYER_FOR_KRAKEN', 'MUST_SELECT_NEW_PLAYER_FOR_KRAKEN');
define('CANCEL_RECRUIT', 'CANCEL_RECRUIT');
const FIGHTED_LEVIATHAN = 'FIGHTED_LEVIATHAN';
const ALLY_FOR_FIGHT = 'ALLY_FOR_FIGHT';
const ATTACK_POWER = 'ATTACK_POWER';
const SLAYED_LEVIATHANS = 'SLAYED_LEVIATHANS';
const REMAINING_REWARDS = 'REMAINING_REWARDS';
const PLAYER_LEVIATHAN_DAMAGE = 'PLAYER_LEVIATHAN_DAMAGE';
const LAST_DIE_ROLL = 'LAST_DIE_ROLL';
const STATE_AFTER_CHOOSE_COUNCIL_STACK_MONSTER_TOKEN = 'STATE_AFTER_CHOOSE_COUNCIL_STACK_MONSTER_TOKEN';
const CURRENT_ATTACK_POWER_ARGS = 'CURRENT_ATTACK_POWER_ARGS';

?>
