<?php

/*
 * State constants
 */
define('ST_BGA_GAME_SETUP', 1);

define('ST_PRE_TURN', 19);
define('ST_PLAYER_PLOT_AT_COURT', 2);
define('ST_PLAYER_ACTION', 3);
define('ST_PLAYER_SECOND_STACK', 32);
define('ST_PRE_PURCHASE', 4);
define('ST_PLAYER_PURCHASE', 5);
define('ST_PRE_EXPLORE', 6);
define('ST_PLAYER_POST_PURCHASE_DISCARD', 62);
define('ST_POST_PURCHASE', 61);
define('ST_PLAYER_EXPLORE', 7);
define('ST_PLAYER_EXPLORE2', 71);
define('ST_PLAYER_EXPLORE3', 72);
define('ST_PRE_CONTROL', 8);
define('ST_PLAYER_CONTROL', 9);
define('ST_NEXT_PLAYER', 10);
define('ST_PLAYER_CHOOSE_MONSTER_REWARD', 11);
define('ST_PLAYER_RECRUIT_PAY', 12);
define('ST_PLAYER_AFFILIATE', 13);
define('ST_PLAYER_LORD_EFFECT', 14);
define('ST_PLAYER_CLEANUP_DISCARD', 15);
define('ST_PLAYER_CONTROL_POST_DRAW', 16);
define('ST_PLAYER_LOCATION_EFFECT_BLACK_SMOKERS', 17);
define('ST_PLAYER_UNUSED_LORDS', 18);
define('ST_PLAYER_MARTIAL_LAW', 20);
define('ST_PLAYER_FILL_SANCTUARY', 21);

define('ST_MULTI_LORD2', 102);
define('ST_PLAYER_LORD4', 104);
define('ST_MULTI_LORD5', 105);
define('ST_PLAYER_LORD7', 107);
define('ST_PLAYER_LORD16', 116);
define('ST_PLAYER_LORD19', 119);
define('ST_PLAYER_LORD19B', 1192);
define('ST_PLAYER_LORD22', 122);
define('ST_PLAYER_LORD23', 123);
define('ST_PLAYER_LORD23B', 1232);
define('ST_PLAYER_LORD26', 126);
define('ST_PLAYER_LORD12', 112);
define('ST_PLAYER_LORD17', 117);
define('ST_PLAYER_LORD21', 121);
define('ST_PLAYER_LORD104', 1104);
define('ST_PLAYER_LORD112', 1112);
define('ST_PLAYER_LORD114', 1114);
define('ST_MULTI_LORD114', 1194);
define('ST_PLAYER_LORD116', 1116);

define('ST_FINAL_SCORING', 98);
define('ST_END_GAME', 99);
define('END_SCORE', 100);

/**
 * Game options
 */
define('KRAKEN_EXPANSION', 110);

/**
 * Constants
 */
define('MARTIAL_LAW_ACTIVATED', 'MARTIAL_LAW_ACTIVATED');
define('LAST_LOCATION', 'LAST_LOCATION');

/**
 * Global variables
 */
define('SENTINELS', 'SENTINELS');

?>
